services:
  - type: web
    name: travel-journal
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: FLASK_ENV
        value: production
